export const BUSINESS_INFO = {
  name: "Walsingham Meat Market",
  phone: "(727) 581-4455",
  address: "11561 Walsingham Rd # H, Largo, FL 33778",
  hours: [
    { day: "Mon - Sat", time: "9:00 AM - 7:00 PM" },
    { day: "Sunday", time: "9:00 AM - 4:00 PM" },
  ],
};

export const HOMEPAGE_MEAT_PLANS = [  
  {
    id: "family-bundle",
    title: "Family Bundle",
    weight: "25 lbs",
    price: "$185",
    description: "Perfect for a family of four for two weeks.",
    items: [
      "5 lbs Ground Beef",
      "4 lbs Sirloin Steaks",
      "4 lbs Chicken Breasts",
      "4 lbs Pork Chops",
      "4 lbs Pot Roast",
      "4 lbs Bacon",
    ],
    featured: false,
  },
  {
    id: "freezer-filler",
    title: "Freezer Filler",
    weight: "50 lbs",
    price: "$350",
    description: "Stock up and save on our most popular cuts.",
    items: [
      "10 lbs Ground Beef",
      "8 lbs Ribeye Steaks",
      "8 lbs Chicken Thighs",
      "8 lbs Pork Loin",
      "8 lbs Beef Brisket",
      "8 lbs Italian Sausage",
    ],
    featured: true,
  },
  {
    id: "quarter-beef",
    title: "Quarter Beef",
    weight: "100-120 lbs",
    price: "$750",
    description: "The ultimate value for the serious meat lover.",
    items: [
      "Assorted Steaks (T-Bone, Ribeye, Sirloin)",
      "Roasts (Chuck, Rump, Pot)",
      "Ground Beef (approx. 40 lbs)",
      "Stew Meat & Short Ribs",
      "Custom cutting available",
    ],
    featured: false,
  },
];

export const ALL_MEAT_PLANS = [
  {
    id: "plan-1",
    title: "Plan No. 1",
    price: "$34.99",
    items: [
      "2lb Ground Beef",
      "2lb Sausage",
      "2lb Turkey Wings",
      "2lb End Cut Pork Chops",
      "2lb Neck Bones",
      "2lb Chicken Wings",
      "2lb Chicken Gizzards",
    ],
    bonus: "Free 2 Liter Soda",
  },
  {
    id: "plan-2",
    title: "Plan No. 2",
    price: "$49.99",
    items: [
      "2lb Chicken Wings",
      "2lb Ground Beef",
      "2lb End Cut Pork Chops",
      "2lb Country Style Ribs",
      "2lb Chicken Breast B/S",
      "2lb Sausage",
      "2lb Bacon",
    ],
    bonus: "Free 2 Liter Soda",
  },
  {
    id: "plan-3",
    title: "Plan No. 3",
    price: "$59.99",
    items: [
      "2lb Bacon",
      "2lb Ground Beef",
      "2lb End Cut Pork Chops",
      "2lb Chicken Wings",
      "2lb Smoked Neck Bones",
      "2lb Beef Stew",
      "2lb Sausage",
      "3lb Rib Tips",
    ],
    bonus: "Free 3lb Bag of Rice",
  },
  {
    id: "plan-4-bbq",
    title: "Plan No. 4 BBQ Special",
    price: "$84.99",
    items: [
      "1 Slab of Ribs",
      "5lb Chicken Wings",
      "5lb Chicken Leg Qtrs",
      "5lb Chicken Drums",
      "5lb Ground Beef",
      "1 PK Hot Dogs",
    ],
    bonus: "Free 18 oz BBQ Sauce & 2 Liter of Soda",
  },
  {
    id: "plan-5",
    title: "Plan No. 5",
    price: "$84.99",
    items: [
      "2lb Round Steak",
      "2lb Ox-Tail",
      "2lb Ground Beef",
      "2lb Chicken Drums",
      "2lb Center Cut Pork Chops",
      "2lb Rib Bacon",
      "2lb Beef Stew",
      "2lb Box Beef Sausage",
      "1 Whole Chicken",
    ],
    bonus: "Free Case Faygo Soda Cans",
  },
  {
    id: "plan-6-steak",
    title: "Plan No. 6 Steak Plan",
    price: "$89.99",
    items: [
      "2lb T-Bone Steak",
      "2lb Rib Eye",
      "2lb Round Steak",
      "2lb New York Strip Steak",
      "2lb Chuck Steak",
      "2lb Pork Steak",
      "2lb Ham Steak",
    ],
    bonus: "Free 6 pk Soda",
  },
  {
    id: "plan-7",
    title: "Plan No. 7",
    price: "$109.99",
    items: [
      "1 Slab Of Ribs",
      "3lb Center Cut Pork Chops",
      "3lb Ground Beef",
      "3lb Stew Beef",
      "3lb Ox-Tail",
      "2lb Chuck Roast",
      "2lb Sausage",
      "2lb Chicken Wings",
      "2lb Turkey Wings",
      "2lb Chicken Breast B/S",
      "1 Whole Chicken",
    ],
    bonus: "Free 3lb Bag Rice & 6 pk Soda",
  },
  {
    id: "plan-8",
    title: "Plan No. 8",
    price: "$114.99",
    items: [
      "3lb Ground Beef",
      "3lb Round Steak",
      "3lb Chicken Wings",
      "3lb Sausage",
      "3lb Bacon",
      "3lb Turkey Necks",
      "3lb Center Cut Pork Chops",
      "3lb Chicken Leg",
      "2lb Stew Meat",
      "3lb Rib Tips",
      "2lb Breakfast Ham Steak",
    ],
    bonus: "Free Jar Yellow Rice",
  },
  {
    id: "plan-9",
    title: "Plan No. 9",
    price: "$149.99",
    items: [
      "1 Slab of Ribs",
      "3lb Ground Beef",
      "3lb Sausage",
      "2lb Bacon",
      "2lb New York Strip Steak",
      "2lb Tilapia",
      "2lb Bag Shrimp",
      "4lb Chicken Leg Qtrs",
      "3lb Turkey Wings",
      "2lb Round Steak",
      "3lb Chuck Roast",
      "2lb Ox-Tail",
    ],
    bonus: "Free 1/2 Gallon BBQ Sauce",
  },
  {
    id: "plan-10",
    title: "Plan No. 10",
    price: "$179.99",
    items: [
      "5lb Uncle Johns Sausage",
      "1 Slab Baby Back Ribs",
      "3lb Ground Beef",
      "3lb Bacon",
      "3lb Box Sausage Patties",
      "3lb Ox-Tails",
      "3lb Chicken Drums",
      "3lb Chicken Breast B/S",
      "3lb Rib Tips",
      "3lb Center Cut Pork Chops",
      "3lb Turkey Wings",
      "3lb New York Strip",
    ],
    bonus: "Free 5lb Bag Rice & 6 Pack Soda",
  },
  {
    id: "plan-11",
    title: "Plan No. 11",
    price: "$199.99",
    items: [
      "5lb T-Bone Steak",
      "5lb Chuck Roast",
      "5lb Turkey Wings",
      "5lb Ground Beef",
      "5lb Chicken Wings",
      "5lb Chicken Drumsticks",
      "5lb Chicken Breast B/S",
      "5lb End Cut Pork Chops",
      "5lb Bacon",
      "5lb Sausage",
      "1 Slab of Ribs",
    ],
    bonus: "Free Case Faygo Soda Cans & 1/2 Gallon BBQ Sauce",
  },
  {
    id: "seafood-combo",
    title: "Seafood Combo",
    price: "$89.99",
    items: [
      "2lb Bag of Shrimp",
      "2lb Snow Crab Legs",
      "2lb Tilapia Filet",
      "2lb Crawfish",
      "2lb Bag of Scallops",
      "2lb Bag of Clams",
    ],
    bonus: "Free 16oz Shrimp & Crab Boil Season",
  },
];

export const PICK_FIVE = {
  title: "Pick Any 5 Items",
  price: "$24.99",
  pickCount: 5,
  items: [
    "1lb Bacon",
    "4lb Fresh Neck Bones",
    "4lb Chicken Leg Qtr",
    "3lb Turkey Necks",
    "3lb Chicken Gizzards",
    "3lb Rib Tips",
    "2lb End Cut Pork Chops",
    "2lb Smoked Neck Bones",
    "1.5lb Ground Beef",
    "2lb PKG Hot Dogs",
    "2lb Country Style Ribs",
    "2lb Beef Livers",
    "2lb Pack Red Hots",
    "1lb American Cheese",
    "2.5lb French Fries",
    "1lb Stew Beef",
    "1.75lb Andy Sausage",
    "2lb Ground Sausage",
    "3lb Chicken Drums",
    "3lb Pig Feet",
    "1.5lb Chicken Wings",
    "1.5lb Chicken Breast B/S",
    "1 Whole Chicken",
    "1lb Frozen Blue Crab",
    "3lb Turkey Wings",
    "1lb Tilapia Filet",
    "2lb Pork Steak",
    "3lb Bag of Rice",
    "1lb Clams",
    "1lb Mussels",
    "21oz Sausage Patties",
  ],
};

export const DEAL_SECTIONS = [
  {
    id: "by-the-case",
    title: "By The Case",
    type: "single" as const,
    items: [
      { name: "40lb Box Chicken Leg Qtr", price: "$37.99" },
      { name: "40lb Box Chicken Drumsticks", price: "$37.99" },
      { name: "40lb Box Chicken Wings", price: "Call" },
      { name: "10lb Box Uncle John Sausage", price: "$44.99" },
      { name: "10lb Box Alabama Sausage", price: "$49.99" },
    ],
  },
  {
    id: "poultry-special",
    title: "Poultry Special",
    type: "tiered" as const,
    items: [
      { name: "Chicken Leg Qtr", price5: "$5.99", price10: "$9.99" },
      { name: "Chicken Wings", price5: "$14.99", price10: "$27.99" },
      { name: "Chicken Drumsticks", price5: "$5.99", price10: "$9.99" },
      { name: "Turkey Wings", price5: "$11.99", price10: "$22.99" },
      { name: "Turkey Necks", price5: "$8.99", price10: "$16.99" },
      { name: "B/S Chicken Breast", price5: "$14.99", price10: "$28.99" },
    ],
  },
  {
    id: "usda-beef-special",
    title: "USDA Beef Special",
    type: "single" as const,
    items: [
      { name: "5lb T-Bone Steak", price: "$35.99" },
      { name: "Rib Eye", price: "$9.99" },
      { name: "Whole Brisket (per lb)", price: "$5.99" },
      { name: "1lb Filet Mignon", price: "$12.99" },
      { name: "1lb Oxtail", price: "$9.99" },
      { name: "1lb Chuck Roast", price: "$4.99" },
      { name: "1lb Beef Stew", price: "$5.99" },
      { name: "5lb Ground Beef", price: "$16.99" },
      { name: "5lb Cube Steak", price: "$35.99" },
      { name: "5lb Beef Short Ribs", price: "$37.99" },
      { name: "5lb New York Strip", price: "$39.99" },
    ],
  },
  {
    id: "pork-special",
    title: "Pork Special",
    type: "tiered" as const,
    items: [
      { name: "Fresh Neck Bones", price5: "$5.99", price10: "$9.99" },
      { name: "Pig Feet", price5: "$7.99", price10: "$13.99" },
      { name: "Rib Tips", price5: "$7.99", price10: "$14.99" },
      { name: "5lb Clean Chittlening", price5: null, price10: "$10.99" },
      { name: "5lb Uncle Johns Sausage", price5: null, price10: "$22.99" },
      { name: "5lb Smoked Bacon", price5: null, price10: "$22.99" },
      { name: "5lb Center Cut Pork Chops", price5: null, price10: "$11.99" },
      { name: "5lb End Cut Pork Chops", price5: null, price10: "$9.99" },
    ],
  },
];